from enum import Enum
import numpy as np
from pandas import read_csv

class Technology(Enum):
    SOLAR_ONLY = 1
    SOFC = 2
    DIESEL = 3
    STORAGE_ONLY = 4

# The max that the system is capable of outputting per hour.
PVWATTS_HOURLY_8760 = read_csv("pvwatts_hourly_8760.csv")

SOFC_POWER_OUTPUT = 10000
DIESEL_POWER_OUTPUT = 10000

STORAGE_MAX_DISCHARGE_RATE = 5000
STORAGE_ENERGY_CAPACITY = 13500

SOLAR_ONLY_FIXED_COST = 12912
SOFC_FIXED_COST = 30000
DIESEL_FIXED_COST = 3900
STORAGE_ONLY_FIXED_COST =  11500

SOLAR_ONLY_VARIABLE_COST = 0
SOFC_VARIABLE_COST = 0.058
DIESEL_VARIABLE_COST = 0.3905
STORAGE_ONLY_VARIABLE_COST = 0

SOLAR_ONLY_CO2 = 0
SOFC_CO2 = 0.771618
DIESEL_CO2 = 1.555
STORAGE_ONLY_CO2 = 0

SOLAR_ONLY_NOx = 0
SOFC_NOx = 0
DIESEL_NOx = 0.00042
STORAGE_ONLY_NOx = 0

SOLAR_ONLY_PM = 0
SOFC_PM = 0
DIESEL_PM = 0.00007
STORAGE_ONLY_PM = 0

SOLAR_ONLY_SO2 = 0
SOFC_SO2 = 0
DIESEL_SO2 = 0.000016
STORAGE_ONLY_SO2 = 0

# TECH_LABELS = {Technology.SOLAR_STORAGE:"3.8kW Solar + 14 kWh Storage System", Technology.SOFC: "10 kW Solid-Oxide Fuel Cell", Technology.DIESEL: "10 kW Diesel Generator"}
TECH_LABELS = {Technology.SOLAR_ONLY:"Solar", Technology.SOFC: "SOFC", Technology.DIESEL: "Diesel", Technology.STORAGE_ONLY:"Battery"}
FIXED_COSTS = {Technology.SOLAR_ONLY:SOLAR_ONLY_FIXED_COST, Technology.SOFC:SOFC_FIXED_COST, Technology.DIESEL: DIESEL_FIXED_COST, Technology.STORAGE_ONLY:STORAGE_ONLY_FIXED_COST}
VARIABLE_COSTS = {Technology.SOLAR_ONLY:SOLAR_ONLY_VARIABLE_COST, Technology.SOFC:SOFC_VARIABLE_COST, Technology.DIESEL: DIESEL_VARIABLE_COST, Technology.STORAGE_ONLY:STORAGE_ONLY_VARIABLE_COST}
CO2_INTENSITY = {Technology.SOLAR_ONLY:SOLAR_ONLY_CO2, Technology.SOFC:SOFC_CO2, Technology.DIESEL: DIESEL_CO2, Technology.STORAGE_ONLY:STORAGE_ONLY_CO2}
NOX_AIR_POLLUTANT_INTENSITY = {Technology.SOLAR_ONLY:SOLAR_ONLY_NOx, Technology.SOFC:SOFC_NOx, Technology.DIESEL: DIESEL_NOx, Technology.STORAGE_ONLY:STORAGE_ONLY_NOx}
PM_AIR_POLLUTANT_INTENSITY = {Technology.SOLAR_ONLY:SOLAR_ONLY_PM, Technology.SOFC:SOFC_PM, Technology.DIESEL: DIESEL_PM, Technology.STORAGE_ONLY:STORAGE_ONLY_PM}
SO2_AIR_POLLUTANT_INTENSITY = {Technology.SOLAR_ONLY:SOLAR_ONLY_SO2, Technology.SOFC:SOFC_SO2, Technology.DIESEL: DIESEL_SO2, Technology.STORAGE_ONLY:STORAGE_ONLY_SO2}

CRITERIA = ['Economic Cost', 'CO2 Pollution', 'NOx Air Pollution', 'PM Air Pollution', 'SO2 Air Pollution', 'CNSP', 'EWOMP']